import type {
  AgentSceneSnapshot,
  LionsDenAgent,
  NavigationEdge,
  NavigationNode,
  OfficeZone,
  WorkEvent,
} from "./types";

export const officeZones: OfficeZone[] = [
  { id: "atlas-command", name: "ATLAS Command", kind: "command", x: 39, y: 5, width: 22, height: 20 },
  { id: "opportunity-bay", name: "Opportunity Bay", kind: "research", x: 6, y: 28, width: 26, height: 24 },
  { id: "content-studio", name: "Content Studio", kind: "creative", x: 37, y: 61, width: 26, height: 24 },
  { id: "crm-corner", name: "CRM Corner", kind: "crm", x: 69, y: 28, width: 25, height: 24 },
  { id: "strategy-table", name: "Lion's Den Table", kind: "meeting", x: 37, y: 32, width: 26, height: 18 },
  { id: "approval-rail", name: "Approval Rail", kind: "approval", x: 68, y: 61, width: 26, height: 16 },
  { id: "revenue-board", name: "Revenue Signals", kind: "revenue", x: 68, y: 79, width: 26, height: 14 },
  { id: "mission-board", name: "Mission Board", kind: "mission", x: 7, y: 79, width: 26, height: 14 },
  { id: "central-hall", name: "Central Hall", kind: "hall", x: 34, y: 25, width: 32, height: 34 },
];

export const navigationNodes: NavigationNode[] = [
  { id: "atlas-desk", label: "Atlas desk", zoneId: "atlas-command", x: 50, y: 14, meaning: "Chief of Staff reviews the mission." },
  { id: "atlas-context", label: "Context wall", zoneId: "atlas-command", x: 42, y: 10, meaning: "Business profile and goals." },
  { id: "atlas-approval", label: "Approval queue", zoneId: "atlas-command", x: 58, y: 19, meaning: "Founder approval before outside action." },
  { id: "north-junction", label: "North junction", zoneId: "central-hall", x: 50, y: 28, meaning: "Main executive hallway." },
  { id: "meeting-head", label: "Meeting head", zoneId: "strategy-table", x: 50, y: 37, meaning: "Atlas receives handoffs." },
  { id: "meeting-left", label: "Research seat", zoneId: "strategy-table", x: 40, y: 42, meaning: "Hunter presents findings." },
  { id: "meeting-right", label: "CRM seat", zoneId: "strategy-table", x: 60, y: 42, meaning: "David reports customer movement." },
  { id: "meeting-bottom", label: "Creative seat", zoneId: "strategy-table", x: 50, y: 49, meaning: "Micah submits marketing drafts." },
  { id: "west-hall", label: "West hall", zoneId: "central-hall", x: 32, y: 42, meaning: "Route to opportunity work." },
  { id: "east-hall", label: "East hall", zoneId: "central-hall", x: 68, y: 42, meaning: "Route to CRM and approvals." },
  { id: "south-junction", label: "South junction", zoneId: "central-hall", x: 50, y: 59, meaning: "Route to content and revenue." },
  { id: "hunter-desk", label: "Hunter desk", zoneId: "opportunity-bay", x: 19, y: 37, meaning: "Opportunity research." },
  { id: "hunter-scan", label: "Signal scanner", zoneId: "opportunity-bay", x: 12, y: 31, meaning: "Reviews fit signals and local demand." },
  { id: "hunter-report", label: "Report stand", zoneId: "opportunity-bay", x: 25, y: 49, meaning: "Opportunity snapshot ready." },
  { id: "micah-desk", label: "Micah desk", zoneId: "content-studio", x: 50, y: 73, meaning: "Campaign drafting." },
  { id: "micah-calendar", label: "Content calendar", zoneId: "content-studio", x: 41, y: 67, meaning: "Approved content schedule." },
  { id: "micah-assets", label: "Asset board", zoneId: "content-studio", x: 59, y: 80, meaning: "Captions, hooks, scripts, prompts." },
  { id: "david-desk", label: "David desk", zoneId: "crm-corner", x: 81, y: 37, meaning: "CRM and follow-up queue." },
  { id: "david-pipeline", label: "Pipeline board", zoneId: "crm-corner", x: 74, y: 31, meaning: "Deals and customer stages." },
  { id: "david-clock", label: "Follow-up clock", zoneId: "crm-corner", x: 88, y: 49, meaning: "Overdue next steps." },
  { id: "approval-desk", label: "Founder approval", zoneId: "approval-rail", x: 79, y: 69, meaning: "Manny approves before external action." },
  { id: "revenue-leak", label: "Revenue leak", zoneId: "revenue-board", x: 77, y: 86, meaning: "Money likely lost to slow follow-up." },
  { id: "revenue-win", label: "Revenue win", zoneId: "revenue-board", x: 88, y: 86, meaning: "Opportunity moved toward cash." },
  { id: "mission-start", label: "New mission", zoneId: "mission-board", x: 16, y: 86, meaning: "Business assessment becomes work." },
  { id: "mission-priority", label: "Priority lock", zoneId: "mission-board", x: 27, y: 86, meaning: "One measurable next move." },
  { id: "handoff-west", label: "West handoff", zoneId: "central-hall", x: 36, y: 54, meaning: "Research turns into campaign work." },
  { id: "handoff-east", label: "East handoff", zoneId: "central-hall", x: 64, y: 54, meaning: "Campaign turns into follow-up work." },
  { id: "review-loop", label: "Review loop", zoneId: "approval-rail", x: 70, y: 69, meaning: "Drafts stay private until approved." },
  { id: "client-safe", label: "Client safe", zoneId: "approval-rail", x: 90, y: 69, meaning: "Private data boundary." },
];

export const navigationEdges: NavigationEdge[] = [
  { from: "atlas-desk", to: "atlas-context" },
  { from: "atlas-desk", to: "atlas-approval" },
  { from: "atlas-desk", to: "north-junction" },
  { from: "north-junction", to: "meeting-head" },
  { from: "meeting-head", to: "meeting-left" },
  { from: "meeting-head", to: "meeting-right" },
  { from: "meeting-head", to: "meeting-bottom" },
  { from: "meeting-left", to: "west-hall" },
  { from: "meeting-right", to: "east-hall" },
  { from: "meeting-bottom", to: "south-junction" },
  { from: "west-hall", to: "hunter-desk" },
  { from: "hunter-desk", to: "hunter-scan" },
  { from: "hunter-desk", to: "hunter-report" },
  { from: "hunter-report", to: "meeting-left" },
  { from: "east-hall", to: "david-desk" },
  { from: "david-desk", to: "david-pipeline" },
  { from: "david-desk", to: "david-clock" },
  { from: "david-clock", to: "revenue-leak" },
  { from: "south-junction", to: "micah-desk" },
  { from: "micah-desk", to: "micah-calendar" },
  { from: "micah-desk", to: "micah-assets" },
  { from: "micah-assets", to: "review-loop" },
  { from: "review-loop", to: "approval-desk" },
  { from: "approval-desk", to: "client-safe" },
  { from: "approval-desk", to: "handoff-east" },
  { from: "handoff-east", to: "david-desk" },
  { from: "handoff-west", to: "micah-desk" },
  { from: "hunter-report", to: "handoff-west" },
  { from: "mission-start", to: "mission-priority" },
  { from: "mission-priority", to: "atlas-context" },
  { from: "revenue-leak", to: "revenue-win" },
  { from: "revenue-win", to: "atlas-approval" },
  { from: "west-hall", to: "south-junction" },
  { from: "east-hall", to: "south-junction" },
];

export const lionsDenAgents: LionsDenAgent[] = [
  {
    id: "atlas",
    name: "ATLAS",
    role: "Chief of Staff",
    animal: "Golden Lion",
    homeNodeId: "atlas-desk",
    sprite: "/kingdom-sprites/crops/atlas-front.png",
    portrait: "/kingdom-sprites/crops/atlas-portrait.png",
    accent: "#f8c14a",
    tools: [
      { label: "Supabase ledger", state: "ready" },
      { label: "Approval gate", state: "approval" },
      { label: "OpenAI planning", state: "ready" },
    ],
  },
  {
    id: "hunter",
    name: "HUNTER",
    role: "Opportunity Director",
    animal: "Bald Eagle",
    homeNodeId: "hunter-desk",
    sprite: "/kingdom-sprites/crops/hunter-front.png",
    portrait: "/kingdom-sprites/crops/hunter-portrait.png",
    accent: "#65d6ff",
    tools: [
      { label: "Google Places", state: "planned" },
      { label: "Fit signals", state: "watching" },
      { label: "Research queue", state: "queued" },
    ],
  },
  {
    id: "micah",
    name: "MICAH",
    role: "Marketing Director",
    animal: "Sloth",
    homeNodeId: "micah-desk",
    sprite: "/kingdom-sprites/crops/micah-front.png",
    portrait: "/kingdom-sprites/crops/micah-portrait.png",
    accent: "#b7f7c1",
    tools: [
      { label: "Content drafts", state: "queued" },
      { label: "Brand voice", state: "watching" },
      { label: "Approval first", state: "approval" },
    ],
  },
  {
    id: "david",
    name: "DAVID",
    role: "CRM Director",
    animal: "Wolf",
    homeNodeId: "david-desk",
    sprite: "/kingdom-sprites/crops/david-front.png",
    portrait: "/kingdom-sprites/crops/david-portrait.png",
    accent: "#9ba7ff",
    tools: [
      { label: "CRM table", state: "ready" },
      { label: "Follow-up clock", state: "watching" },
      { label: "Pipeline hygiene", state: "queued" },
    ],
  },
];

export const initialAgentSnapshots: AgentSceneSnapshot[] = [
  {
    agentId: "atlas",
    state: "thinking",
    nodeId: "atlas-desk",
    targetNodeId: "atlas-context",
    currentAssignment: "Turn the assessment into one measurable revenue priority.",
    lastEvent: "Mission received",
    nextExpectedAction: "Assign the first growth investigation.",
  },
  {
    agentId: "hunter",
    state: "available",
    nodeId: "hunter-desk",
    targetNodeId: "hunter-desk",
    currentAssignment: "Standing by for opportunity research.",
    lastEvent: "Ready",
    nextExpectedAction: "Scan for warm lead sources.",
  },
  {
    agentId: "micah",
    state: "available",
    nodeId: "micah-desk",
    targetNodeId: "micah-desk",
    currentAssignment: "Standing by for approved offers.",
    lastEvent: "Ready",
    nextExpectedAction: "Draft private campaign assets.",
  },
  {
    agentId: "david",
    state: "available",
    nodeId: "david-desk",
    targetNodeId: "david-desk",
    currentAssignment: "Watching for leads needing a next step.",
    lastEvent: "Ready",
    nextExpectedAction: "Attach every opportunity to follow-up.",
  },
];

export const demoWorkEvents: WorkEvent[] = [
  {
    id: "evt-001",
    organizationId: "demo-service-company",
    missionId: "mission-revenue-leak",
    workItemId: "assessment-review",
    agentId: "atlas",
    eventType: "mission_received",
    state: "thinking",
    fromNodeId: "mission-start",
    toNodeId: "atlas-context",
    safeSummary: "ATLAS received a business assessment and found the first priority: warm leads are not getting followed up.",
    targetZoneId: "atlas-command",
    nextExpectedAction: "Create one growth mission and assign research to HUNTER.",
    occurredAt: "08:00 AM",
  },
  {
    id: "evt-002",
    organizationId: "demo-service-company",
    missionId: "mission-revenue-leak",
    workItemId: "opportunity-scan",
    agentId: "hunter",
    eventType: "assignment_created",
    state: "walking",
    fromNodeId: "meeting-left",
    toNodeId: "hunter-scan",
    safeSummary: "HUNTER was assigned to find the fastest path to more qualified opportunities.",
    targetAgentId: "atlas",
    targetZoneId: "opportunity-bay",
    nextExpectedAction: "Scan local channels and prepare an opportunity snapshot.",
    occurredAt: "08:03 AM",
  },
  {
    id: "evt-003",
    organizationId: "demo-service-company",
    missionId: "mission-revenue-leak",
    workItemId: "opportunity-snapshot",
    agentId: "hunter",
    eventType: "deliverable_created",
    state: "handing_off",
    fromNodeId: "hunter-report",
    toNodeId: "meeting-left",
    safeSummary: "HUNTER returned a shortlist of warm-lead sources and one recommended next move.",
    deliverableId: "opportunity-snapshot-demo",
    targetAgentId: "atlas",
    targetZoneId: "strategy-table",
    nextExpectedAction: "ATLAS reviews and chooses the offer to test.",
    approvalRequired: true,
    occurredAt: "08:09 AM",
  },
  {
    id: "evt-004",
    organizationId: "demo-service-company",
    missionId: "mission-revenue-leak",
    workItemId: "content-draft",
    agentId: "micah",
    eventType: "approval_granted",
    state: "walking",
    fromNodeId: "meeting-bottom",
    toNodeId: "micah-desk",
    safeSummary: "ATLAS approved the strongest offer. MICAH is turning it into simple marketing drafts.",
    targetAgentId: "atlas",
    targetZoneId: "content-studio",
    nextExpectedAction: "Create private captions, offer angles, and a short CTA.",
    occurredAt: "08:14 AM",
  },
  {
    id: "evt-005",
    organizationId: "demo-service-company",
    missionId: "mission-revenue-leak",
    workItemId: "content-approval",
    agentId: "micah",
    eventType: "approval_requested",
    state: "waiting_for_approval",
    fromNodeId: "micah-assets",
    toNodeId: "approval-desk",
    safeSummary: "MICAH drafted content, but it stays private until ATLAS and the owner approve it.",
    deliverableId: "content-pack-demo",
    targetAgentId: "atlas",
    targetZoneId: "approval-rail",
    nextExpectedAction: "Review draft and approve, reject, or request changes.",
    approvalRequired: true,
    occurredAt: "08:21 AM",
  },
  {
    id: "evt-006",
    organizationId: "demo-service-company",
    missionId: "mission-revenue-leak",
    workItemId: "crm-handoff",
    agentId: "david",
    eventType: "handoff_started",
    state: "walking",
    fromNodeId: "handoff-east",
    toNodeId: "david-desk",
    safeSummary: "DAVID received the approved offer so every response can be tracked with a next step.",
    targetAgentId: "micah",
    targetZoneId: "crm-corner",
    nextExpectedAction: "Create follow-up stages and a simple response tracker.",
    occurredAt: "08:27 AM",
  },
  {
    id: "evt-007",
    organizationId: "demo-service-company",
    missionId: "mission-revenue-leak",
    workItemId: "follow-up-queue",
    agentId: "david",
    eventType: "follow_up_queued",
    state: "working",
    fromNodeId: "david-desk",
    toNodeId: "david-clock",
    safeSummary: "DAVID found three open follow-ups and put them into a visible queue.",
    targetZoneId: "crm-corner",
    nextExpectedAction: "ATLAS reviews the revenue leak before outreach is approved.",
    approvalRequired: true,
    occurredAt: "08:34 AM",
  },
  {
    id: "evt-008",
    organizationId: "demo-service-company",
    missionId: "mission-revenue-leak",
    workItemId: "priority-update",
    agentId: "atlas",
    eventType: "mission_updated",
    state: "completed",
    fromNodeId: "revenue-leak",
    toNodeId: "atlas-approval",
    safeSummary: "ATLAS updated the mission: fix inquiry-to-follow-up first before adding another tool.",
    targetZoneId: "atlas-command",
    nextExpectedAction: "Founder approval decides whether this becomes live work.",
    approvalRequired: true,
    occurredAt: "08:40 AM",
  },
];
