import type { Metadata } from "next";
import Link from "next/link";
import {
  LegalList,
  LegalPage,
  LegalSection,
  legalLinkClass,
} from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy | Atlas For Entrepreneurs",
  description:
    "Learn how Atlas For Entrepreneurs collects, uses, shares, and protects information.",
};

export default function PrivacyPage() {
  return (
    <LegalPage
      eyebrow="Privacy & data"
      lastUpdated="July 16, 2026"
      summary="This policy explains what Atlas collects, why it is needed, when it may be shared, and the choices available to assessment prospects and client workspace users."
      title="Privacy Policy"
    >
      <LegalSection title="1. Scope">
        <p>
          This Privacy Policy applies to Atlas For Entrepreneurs (“Atlas,” “we,”
          “us,” or “our”), this website, the free business assessment, and Atlas
          client workspaces. It does not replace a separate written agreement that
          may apply to paid client services.
        </p>
        <p>
          Atlas is designed for business owners and authorized business users in
          the United States. It is not intended for personal, household, medical,
          financial, employment, credit, or other regulated decision-making uses.
        </p>
      </LegalSection>

      <LegalSection title="2. Information we collect">
        <p>Depending on how you use Atlas, we may collect:</p>
        <LegalList>
          <li>
            <strong>Assessment information:</strong> your description of the
            business, ideal customer, customer sources, challenges, goals,
            evaluation interests, business size, current AI use, and timing.
          </li>
          <li>
            <strong>Contact and business information:</strong> name, business
            name, email address, telephone number, website, optional public social
            media links or handles, and consent to be contacted.
          </li>
          <li>
            <strong>Account and workspace information:</strong> login email,
            organization membership, business profile, plans, actions, drafts,
            review decisions, messages, notes, and activity records created while
            providing the service.
          </li>
          <li>
            <strong>Public Atlas chat information:</strong> questions submitted to
            the homepage preview, Atlas replies, a short-lived browser-session
            identifier, response status, model and token-usage records, and
            estimated API cost used to operate, limit, and evaluate the preview.
          </li>
          <li>
            <strong>Technical information:</strong> essential authentication and
            security cookies, request information, IP address, browser or device
            information, and operational logs generated by our hosting,
            authentication, and security providers.
          </li>
          <li>
            <strong>Public business information:</strong> information from a
            website, social profile, business directory, or other public source
            when you ask Atlas to evaluate or research a business.
          </li>
        </LegalList>
        <p>
          This website does not currently collect payment card details. Please do
          not submit passwords, government identification numbers, payment card
          numbers, medical information, or sensitive personal information through
          an assessment or workspace message.
        </p>
      </LegalSection>

      <LegalSection title="3. How we use information">
        <p>We use information to:</p>
        <LegalList>
          <li>receive and review assessment requests;</li>
          <li>contact you about the request you submitted;</li>
          <li>recommend, provide, and administer Atlas services;</li>
          <li>create and secure accounts and organization workspaces;</li>
          <li>organize approved plans, opportunities, drafts, and reviews;</li>
          <li>prevent misuse, troubleshoot problems, and protect the service;</li>
          <li>improve Atlas workflows and customer support; and</li>
          <li>comply with applicable law and enforce our agreements.</li>
        </LegalList>
        <p>
          We do not use assessment information for a materially different purpose
          without providing appropriate notice and obtaining consent when required.
        </p>
      </LegalSection>

      <LegalSection title="4. How information is shared">
        <p>
          Atlas does not sell personal information and does not share it for
          cross-context behavioral advertising. We may disclose information only
          as reasonably necessary to:
        </p>
        <LegalList>
          <li>
            use service providers for website hosting, database storage,
            authentication, email delivery, security, and technical support;
          </li>
          <li>
            work with contractors or professional advisers who need the
            information to support Atlas and are expected to protect it;
          </li>
          <li>follow your directions or complete an approved client workflow;</li>
          <li>
            comply with law, legal process, or a valid government request, or
            protect rights, safety, and service integrity; or
          </li>
          <li>
            evaluate or complete a business transaction involving Atlas, subject
            to appropriate confidentiality and notice where required.
          </li>
        </LegalList>
        <p>
          Service providers process information for Atlas under their own service
          terms and security obligations. Atlas remains responsible for selecting
          providers appropriate to the information and proposed workflow.
        </p>
        <p>
          When an authorized Atlas administrator deliberately runs the HUNTER
          local-business preview, Atlas sends the entered business type and service
          area to Google Places API. Result content is displayed transiently for
          verification and is not automatically copied into the Atlas CRM. Google
          may process request and usage information under the{" "}
          <a
            className={legalLinkClass}
            href="https://policies.google.com/privacy"
            rel="noreferrer"
            target="_blank"
          >
            Google Privacy Policy
          </a>
          . Atlas separately records the search phrase, request count, result count,
          and estimated list-price exposure for cost control.
        </p>
      </LegalSection>

      <LegalSection title="5. AI-assisted processing">
        <p>
          Submitting an assessment through this website does not automatically send
          the assessment to an external AI model, publish content, contact a lead,
          or make a business decision. Assessment submissions are reviewed before a
          paid scope is proposed.
        </p>
        <p>
          Questions entered into the public Atlas chat preview are sent to OpenAI
          to generate the requested reply. Atlas stores the question, reply,
          operational status, session identifier, and usage record so we can
          provide the preview, prevent misuse, understand what prospects need, and
          control costs. Do not enter confidential or sensitive information into
          the public preview.
        </p>
        <p>
          If a proposed client workflow will use an external AI or data provider,
          Atlas will describe the purpose, approval point, and any separately billed
          external cost before that workflow is activated. Read our{" "}
          <Link className={legalLinkClass} href="/responsible-ai">
            Responsible AI & Human Review
          </Link>{" "}
          page for current operating principles.
        </p>
      </LegalSection>

      <LegalSection title="6. Cookies and similar technology">
        <p>
          Atlas uses cookies that are necessary for secure sign-in, session
          continuity, password recovery, fraud prevention, and enforcement of the
          public chat preview limit. Our infrastructure providers may also create
          operational logs needed to deliver and secure the website.
        </p>
        <p>
          Atlas does not currently use advertising cookies or cross-site targeted
          advertising trackers. If nonessential analytics or advertising technology
          is added, this policy and any required consent choices will be updated
          before that use begins.
        </p>
      </LegalSection>

      <LegalSection title="7. Retention and security">
        <p>
          We retain prospect information for as long as reasonably necessary to
          respond, evaluate fit, maintain appropriate business records, prevent
          abuse, and meet legal obligations. Client information may be retained for
          the duration of the relationship and for a reasonable period afterward.
          Retention periods vary with the record and purpose. We may delete or
          deidentify information when it is no longer reasonably needed, subject to
          legal, security, backup, and dispute-resolution requirements.
        </p>
        <p>
          Atlas uses reasonable administrative, technical, and organizational
          safeguards appropriate to the information maintained, including access
          controls and organization-level data restrictions. No website or storage
          system can guarantee absolute security.
        </p>
      </LegalSection>

      <LegalSection title="8. Your choices and privacy requests">
        <p>
          Depending on where you live and which law applies, you may have the right
          to request access to, correction of, deletion of, or a portable copy of
          personal information, and to appeal a decision about a request. You may
          also ask Atlas to stop nonessential marketing communications at any time.
        </p>
        <p>
          Submit a request by emailing{" "}
          <a
            className={legalLinkClass}
            href="mailto:hello@siscustomcreations.com?subject=Privacy%20request"
          >
            hello@siscustomcreations.com
          </a>{" "}
          with the subject “Privacy request.” We may need to verify your identity or
          authority before acting. If a request is denied, reply with the subject
          “Privacy appeal” and explain why you believe the decision should be
          reconsidered. Atlas will respond within the time required by applicable law.
        </p>
      </LegalSection>

      <LegalSection title="9. Children, changes, and contact">
        <p>
          Atlas is a business service and is not directed to children under 13. We
          do not knowingly collect personal information from children under 13. If
          you believe a child submitted information, contact us so it can be reviewed
          and removed as appropriate.
        </p>
        <p>
          We may update this policy as Atlas changes. The revised version will show
          a new “Last updated” date. Material changes will receive additional notice
          or consent where required.
        </p>
        <p>
          Questions or privacy requests may be sent to{" "}
          <a className={legalLinkClass} href="mailto:hello@siscustomcreations.com">
            hello@siscustomcreations.com
          </a>
          .
        </p>
      </LegalSection>
    </LegalPage>
  );
}
